### ISSUE TITLE
Screen glitch / bug

### ISSUE THREAD

**Issue by JaroslavN** [MateoConLechuga/CEmu#10]
I was putting everything in 1 place and *this* happend :p 
![schermopname 103](https://cloud.githubusercontent.com/assets/16990273/12722895/55c1fd9c-c907-11e5-8a10-873c63b52c0c.png)

**Comment by Runer112** [comment]
I blame Qt, in which case there's not much that we can do to fix it. But perhaps someone else knows more about this.

**Comment by MateoConLechuga** [comment]
You have to unmaximize the window, and then remaximize it, as I have said before.

**Comment by MateoConLechuga** [comment]
I'm just going to close this issue for now, as it is more of a Qt issue rather than a CEmu issue. Will reopen if we care enough :)
