### ISSUE TITLE
cd core;make doesn't work

### ISSUE THREAD

**Issue by elfprince13** [MateoConLechuga/CEmu#6]
It appears the makefile for the code defaults to some incorrect preprocessor flags.

cpu.c:1317:41: warning: implicit declaration of function 'open_debugger' is invalid in C99 [-Wimplicit-function-declaration]
                                        open_debugger(DBG_STEP, 0);
                                        ^
cpu.c:1317:55: error: use of undeclared identifier 'DBG_STEP'
                                        open_debugger(DBG_STEP, 0);

**Comment by adriweb** [comment]
Hm, it's missing an `ifdef DEBUG_SUPPORT` guard. I'll fix that.

**Comment by adriweb** [comment]
Wait, there's one more `debug_read_long` call in link.c ; Fix incoming.
