### ISSUE TITLE
CEmu hangs/pegs CPU if throttling is disabled when the OS is in low power mode

### ISSUE THREAD

**Issue by Runer112** [MateoConLechuga/CEmu#8]
This is probably not explicitly due to anything special about the OS's low power mode, just the emulator running too fast and metaphorically tripping over its own feet somehow.

There may simply be a way to fix something so that the emulator can run at these insane speeds without failing. But if not, a workaround could be to still perform throttling when "disabled," but limit to a very high factor, like 10,000%.

**Comment by MateoConLechuga** [comment]
Fixed by checking if the calculator is off and not sending the speed change update.
