### ISSUE TITLE
CEmu screen issue

### ISSUE THREAD

**Issue by JaroslavN** [MateoConLechuga/CEmu#9]
my screen resolution is 1366 x 768
and this is what happens :l
![schermopname 94](https://cloud.githubusercontent.com/assets/16990273/12704025/d8efe7f8-c851-11e5-9bd6-2ed040316670.png)

somethimes i can't place the screen on top of the keyboard

![schermopname 100](https://cloud.githubusercontent.com/assets/16990273/12704043/500f2484-c852-11e5-965e-d3bf9f4a94e4.png)

**Comment by MateoConLechuga** [comment]
You need to unmaximize the window in the first image, and then remaximize it. The keypad is being redone; and keep in mind this is still in development. Thanks for the info! :)

**Comment by JaroslavN** [comment]
ok, i got it ,but for people ,when it is going to be released ,it is going to be a little bit hard to use it i think :)
![schermopname 102](https://cloud.githubusercontent.com/assets/16990273/12704262/2ad64594-c857-11e5-9942-e6aa7785b584.png)

**Comment by Runer112** [comment]
I made a change earlier today that reduced the minimum allowed keypad size. You should now be able to dock the keypad below the screen, even at very low vertical resolutions. For instance, here's a screenshot taken at 1280x720:

![http://i.imgur.com/SHR09Ql.png](http://i.imgur.com/SHR09Ql.png)
